# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI/CD Production

env:
  DATABASE_URL: "postgresql://admin:vq012mv9@localhost:5432/database?schema=public"

on:
  push:
    branches: [ main ]
    paths:
      - backend/**
      - .github/workflows/hello-world.yaml

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: backend
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: "npm"
        cache-dependency-path: 'backend/package-lock.json'
    - run: npm install
    - run: npm run migrate:deploy
